### PR TITLE
Added edit functionality and popup to show details.

### PR DESCRIPTION
**Pull request by pragatipant**
Test plan:

- Check out branch viewDetails
- Pull latest code
- Do npm install
- Do npm start
- Verify app loads locally
- Add a task to the list
- Add another task from the list
- Edit the first task. Add a new title and new details.
- Edit the second task. Add a new title and new details.
- Click on view for first task. Verify you can see the new title/details.
- Click on view for second task. Verify you can see the new title/details.

### CODE REVIEW

**Comment by chloedeveloper** [comment]
I tried to review the pull request, and am not sure if I did something wrong, but here is the error I am getting after pulling the branch:

Failed to compile.

Module not found: Error: Can't resolve 'reactjs-popup' in '/Users/chloejohnson/listify/listify/src'
ERROR in ./src/ListComponent.js 14:0-34
Module not found: Error: Can't resolve 'reactjs-popup' in '/Users/chloejohnson/listify/listify/src'

ERROR in ./src/ListComponent.js 15:0-38
Module not found: Error: Can't resolve 'reactjs-popup/dist/index.css' in '/Users/chloejohnson/listify/listify/src'

webpack compiled with 2 errors

**Comment by chloedeveloper** [comment]
May need to meet later today and do a screen share to see whats happening

**Comment by ectherrien** [comment]
Maybe need to do an npm install? No idea, will try and report back if I can get it working.

**Comment by ectherrien** [comment]
Yeah I think npm install will fix your issues @chloedeveloper, that worked for me at least.

**Comment by ectherrien** [comment]
so I am seeing some weird behavior, when I hit edit I enter some text and then hit 'ok' the popup comes up a second time. I have tried entering different text each time and only the first text entered is saved it seems. We can discuss tonight.

**Review by ectherrien — APPROVED** [review]
Tested, worked!

**Pull request merged**
